### ISSUE TITLE
ValueError: Fn::Select not allowed to be nested in Fn::Equals

### ISSUE THREAD

**Issue by chirayu-driod** [DontShaveTheYak/cf2tf#114]
I tried to convert cloudformation yaml file to terraform tf file using command cf2tf abc.yaml > def.tf but getting below error. 

Also i am not able to see terraform code inside def.tf file as it says below , can anyone let me know where i can find my terraform code after conversion ?
=============================
[root@ip-172- ec2-user]# cat def.tf 
// Cloning Terraform src code to /var/tmp/terraform_src...
 code has been checked out.
[root@ip-172ec2-user]# 
==========================================

[root@ip-172- ec2-user]# cf2tf abc.yaml > def.tf
// Converting abc.yaml to Terraform!
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 94, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 146, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 271, in convert_conditions
    resolved_values = self.resolve_values(dict_conditons, functions.ALL_FUNCTIONS)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 181, in resolve_values
    data[key] = self.resolve_values(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 189, in resolve_values
    value = self.resolve_values(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 197, in resolve_values
    resolved_list_values = [
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 198, in <listcomp>
    self.resolve_values(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 189, in resolve_values
    value = self.resolve_values(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 197, in resolve_values
    resolved_list_values = [
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 198, in <listcomp>
    self.resolve_values(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 187, in resolve_values
    raise ValueError(f"{key} not allowed to be nested in {prev_func}.")
ValueError: Fn::Select not allowed to be nested in Fn::Equals.

**Comment by jignesh1995** [comment]
I think you have a line in your Cloudformation template which is like:

```
SomeCondition: !Equals
    - !Select [...]
```

This format(!Select within !Equals) is not supported for conversion based on what I see in `convert.py` (Probably because it is not supported as per [Cloudformation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#w2ab1c33c28c21c29) as well).

You can try to remove the `!Select` statement in you Cloudformation template and then add a corresponding logic manually once the terraform script gets generated.

**Comment by shadycuz** [comment]
@chirayu-driod If you are positive that your Cloudformation is valid, than I will adjust the logic to allow the `Select` statement inside of an `Equals` statement.

When I get time I will also manually verify that it works. 

Thanks for opening the issue.

**Comment by umbertix** [comment]
I've runned into the same error while trying to use an example file from the AWS official documentation, maybe it would help as a file example.
The file that I'm refering to is: https://aws-quickstart.s3.amazonaws.com/quickstart-linux-bastion/templates/linux-bastion-entrypoint-existing-vpc.template.yaml

And the source of it, is this official post: https://aws.amazon.com/solutions/implementations/linux-bastion/

Hope this helps ;)

**Comment by shadycuz** [comment]
This has been fixed in #193 and will be released soon.

**Comment by RedaElHajjaji** [comment]
Hey @shadycuz 
when will it be released?

**Comment by shadycuz** [comment]
@RedaElHajjaji last night https://github.com/DontShaveTheYak/cf2tf/releases/tag/0.6.0
