### ISSUE TITLE
Unable to convert to TF

### ISSUE THREAD

**Issue by jalagars** [DontShaveTheYak/cf2tf#137]
/ Converting dev2x_cf.yaml to Terraform!
Traceback (most recent call last):
  File "/opt/homebrew/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 92, in convert
    tf_resources = self.convert_to_tf(self.manifest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 139, in convert_to_tf
    tf_resources.extend(converter(resources))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 316, in convert_resources
    resolved_values = self.resolve_values(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 172, in resolve_values
    data[key] = self.resolve_values(
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 172, in resolve_values
    data[key] = self.resolve_values(
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 188, in resolve_values
    resolved_list_values = [
                           ^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 189, in <listcomp>
    self.resolve_values(
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 172, in resolve_values
    data[key] = self.resolve_values(
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 180, in resolve_values
    value = self.resolve_values(
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 188, in resolve_values
    resolved_list_values = [
                           ^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 189, in <listcomp>
    self.resolve_values(
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 188, in resolve_values
    resolved_list_values = [
                           ^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 189, in <listcomp>
    self.resolve_values(
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 167, in resolve_values
    return functions.ref(self, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/conversion/expressions.py", line 831, in ref
    _, valid_attributes = doc_file.parse_attributes(docs_path)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 15, in parse_attributes
    attributes = parse_section("Attributes Reference", file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 37, in parse_section
    items = parse_items(file)
            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 69, in parse_items
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in * `replica.*.arn` - ARN of the replica

**Comment by shadycuz** [comment]
This looks to be identical to #113, I will close this in favor of that issue. I will try and fix this bug soon. Thanks for opening up the issue @jalagars and if you think these bugs are different then feel free to let me know and I will re-open this issue. 

Thanks
