### ISSUE TITLE
Errors to convert RH provided cloud formation templates

### ISSUE THREAD

**Issue by jauyzed** [DontShaveTheYak/cf2tf#151]
Hello,

I'm trying to convert these yamls: 
https://github.com/openshift/installer/blob/master/upi/aws/cloudformation/04_cluster_bootstrap.yaml
https://github.com/openshift/installer/blob/master/upi/aws/cloudformation/05_cluster_master_nodes.yaml

Seeing this error: 

```
Traceback (most recent call last):
  File "/home/jauyzed/.local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/home/jauyzed/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/convert.py", line 92, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/convert.py", line 139, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/convert.py", line 297, in convert_resources
    valid_arguments, valid_attributes = doc_file.parse_attributes(docs_path)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/terraform/doc_file.py", line 13, in parse_attributes
    arguments = parse_section("Argument Reference", file)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/terraform/doc_file.py", line 37, in parse_section
    items = parse_items(file)
  File "/home/jauyzed/.local/lib/python3.8/site-packages/cf2tf/terraform/doc_file.py", line 69, in parse_items
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in **attributes** supports the following attributes
```

Please test the other CF templates in this repo: https://github.com/openshift/installer/tree/master/upi/aws/cloudformation

Thanks!

**Comment by shadycuz** [comment]
04 and 05 convert without error for me on the latest version. The conversions are not 100% accurate thought. Feel free to open new issues for specific things like:

`// CF Property(TargetIp) = aws_instance.master1.private_ip` not being translated properly.
