### ISSUE TITLE
ValueError: Fn::Cidr not allowed to be nested in Fn::Select.

### ISSUE THREAD

**Issue by HennessyWorks** [DontShaveTheYak/cf2tf#221]
Getting the following error:

// Converting conversions-api-gateway.eks_multiaccount_dual_nat.yaml to Terraform!
  [##----------------------------------]    5%  00:03:19 code has been checked out.erraform_src...
Traceback (most recent call last):
  File "/opt/homebrew/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 92, in convert
    tf_resources = self.convert_to_tf(self.manifest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 139, in convert_to_tf
    tf_resources.extend(converter(resources))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 319, in convert_resources
    resolved_values = self.resolve_values(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 172, in resolve_values
    data[key] = self.resolve_values(
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 180, in resolve_values
    value = self.resolve_values(
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 191, in resolve_values
    resolved_list_values = [
                           ^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 192, in <listcomp>
    self.resolve_values(
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 178, in resolve_values
    raise ValueError(f"{key} not allowed to be nested in {prev_func}.")
ValueError: Fn::Cidr not allowed to be nested in Fn::Select.

Cloudformation file is coming from the following site:

https://conversions-api-gateway-release-production.s3.us-west-2.amazonaws.com/conversions-api-gateway.eks_multiaccount_dual_nat.yaml

Any help would be greatly appreciated

**Comment by shadycuz** [comment]
The AWS documentation states that the `Cidr` function is not allowed to be nested in the `Select`  function. But the AWS docs are usally wrong. We will add this in soon.

**Comment by shadycuz** [comment]
Fixed in 0.6.2, feel free to reopen if you still have issues.
