### ISSUE TITLE
Unable to convert Aurora Cluster CFN Template

### ISSUE THREAD

**Issue by j0nathontayl0r** [DontShaveTheYak/cf2tf#228]
[platform-aurora-cluster.cf.txt](https://github.com/DontShaveTheYak/cf2tf/files/13324450/platform-aurora-cluster.cf.txt)
```
cf2tf platform-aurora-cluster.cf.yml >> ../terraform/platform-aurora-cluster.cf.yml
// Converting platform-aurora-cluster.cf.yml to Terraform!
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 14, in parse_attributes
    arguments = parse_section("Argument Reference", file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 43, in parse_section
    items = parse_items(file)
            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 75, in parse_items
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in * [create-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 92, in convert
    tf_resources = self.convert_to_tf(self.manifest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 139, in convert_to_tf
    tf_resources.extend(converter(resources))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/convert.py", line 300, in convert_resources
    valid_arguments, valid_attributes = doc_file.parse_attributes(docs_path)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 16, in parse_attributes
    raise Exception(f"Unable to find arguments in {file.name}") from e
Exception: Unable to find arguments in /var/folders/p4/dxj96zlj4y977pggkt7q2_gc0000gn/T/terraform_src/website/docs/r/rds_cluster.html.markdown
```

Hoping it helps, I've also attached my Aurora Cluster template though I'd removed the default values in the template for some of our AWS resources.

**Comment by shadycuz** [comment]
We get a little bit more info if we pass the `-v debug` option. 

```
debug: Converting Cloudformation resource RDSDBCluster to Terraform.
debug: Converted name to rdsdb_cluster
debug: Converted CF type AWS::RDS::DBCluster to search term rds db cluster.
debug: Searcing for rds db cluster in terraform docs...
debug: Best match was rds cluster at /tmp/terraform_src/website/docs/r/rds_cluster.html.markdown with score of 88.
debug: Found documentation file /tmp/terraform_src/website/docs/r/rds_cluster.html.markdown
debug: Converted type from AWS::RDS::DBCluster to aws_rds_cluster
```

The smoking gun is in the stack trace:
```
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in * [create-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html)
```

cf2tf works by taking the cloudformation resources in your template and looking them up in the Terraform documentation. It then parses out the arguments and attributes from that Terraform documentation. The problem here is that Terraform has put some links at the top of the documentation, which breaks the parsing.

> ## Argument Reference
> 
> For more detailed documentation about each argument, refer to
> the AWS official documentation :
> 
> * [create-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html)
> * [modify-db-cluster](https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-cluster.html)
> 
> This argument supports the following arguments:
> 
> * `allocated_storage` - (Optional) (Required for Multi-AZ DB cluster) The amount of storage in gibibytes (GiB) to allocate to each DB instance in the Multi-AZ DB cluster.

This should be an easy fix. Thanks for reporting the issue =)

**Comment by j0nathontayl0r** [comment]
Thank you for replying and making the effort to tell me how cf2tf works :)

**Comment by shadycuz** [comment]
@j0nathontayl0r I will open a PR shortly with the fix, but for now here is the converted Terraform code.

```HCL
data "aws_region" "current" {}

locals {
  DBSnapshotIdentifierIsBlank = var.db_snapshot_identifier == ""
  HasDBSnapshotIdentifier = !local.DBSnapshotIdentifierIsBlank
  IsFakedBranchEnvironment = anytrue([var.environment_tag == "BR", var.environment_tag == "UB"])
  stack_name = "platform-aurora-cluster.cf"
}

variable region_tag {
  description = "Region tag used for StackName and tagging"
  type = string
}

variable stack_integer {
  description = "StackInteger tag"
  type = string
}

variable environment_tag {
  description = "Environment tag used to create the StackName and tagging"
  type = string
}

variable customer_tag {
  description = "Customer tag used to create StackName and resource tagging"
  type = string
}

variable infrastructure_release_tag {
  description = "Release tag (n.n.n) used to signify the stack/version or release an environment is running on, optionally used in a StackName but is not mandatory"
  type = string
}

variable service_layer_tag {
  description = "Tag to describe where in the service architecture a particular resource exists"
  type = string
  default = "NewPlatform"
}

variable aurora_backups_bucket_name {
  description = "The bucket used to store Aurora snapshots/backups"
  type = string
}

variable aurora_min_capacity {
  description = "The aurora scaling max capacity value, refer to here for doco: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.setting-capacity.html#aurora-serverless-v2.max_capacity_considerations"
  type = string
  default = 1
}

variable aurora_max_capacity {
  description = "The aurora scaling max capacity value, refer to here for doco: https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.setting-capacity.html#aurora-serverless-v2.max_capacity_considerations"
  type = string
  default = 10
}

variable aurora_sql_secret_arn {
  description = "The ARN of the secrets resource that contains the password for the master user in the Aurora PostgreSQL cluster"
  type = string
}

variable db_name {
  description = "The name of the DB in the PostgreSQL Aurora cluster"
  type = string
  default = "DingoPlatformDatabase"
}

variable db_snapshot_identifier {
  description = "Optional name or Amazon Resource Name (ARN) of the DB snapshot from which you want to restore (leave blank to create an empty database)."
  type = string
}

variable db_master_username {
  description = "The master user name for the DB instance (ignored when DBSnapshotIdentifier is set, value used from snapshot)."
  type = string
  default = "master"
}

variable engine_version {
  description = "The DB engine to use for the Aurora Serverless cluster"
  type = string
}

variable subnet_private1 {
  description = "Backend subnet (AZ1)"
  type = string
}

variable subnet_private2 {
  description = "Backend subnet (AZ2)"
  type = string
}

variable subnet_private1_availability_zone {
  description = "The availability zone of the private subnet 1"
  type = string
}

variable subnet_private2_availability_zone {
  description = "The availability zone of the private subnet 1"
  type = string
}

variable vpc_id {
  description = "VPC into which the cluster should be deployed"
  type = string
}

variable vpc_cidr {
  description = "The CIDR of the VPC that these resources will reside in, used for security groups"
  type = string
}

resource "aws_security_group" "postgre_sqlrds_security_group" {
  description = "RDS Group"
  vpc_id = var.vpc_id
  ingress = [
    {
      description = "PostgreSQL DB Connection, inbound"
      protocol = "tcp"
      from_port = 5432
      to_port = 5432
      cidr_blocks = var.vpc_cidr
    }
  ]
}

resource "aws_rds_cluster" "rdsdb_cluster" {
  iam_roles = [
    {
      FeatureName = "s3Export"
      RoleArn = aws_iam_role.aurora_role.arn
    }
  ]
  port = 5432
  deletion_protection = False
  storage_encrypted = True
  database_name = var.db_name
  engine = "aurora-postgresql"
  engine_mode = "provisioned"
  engine_version = True
  cluster_identifier = "${local.stack_name}"
  master_user_secret_kms_key_id = {
    SecretArn = var.aurora_sql_secret_arn
  }
  backup_retention_period = 35
  storage_type = "aurora"
  snapshot_identifier = local.HasDBSnapshotIdentifier ? var.db_snapshot_identifier : null
  db_subnet_group_name = aws_db_subnet_group.db_instance_subnet_group.id
  vpc_security_group_ids = [
    aws_security_group.postgre_sqlrds_security_group.arn
  ]
  preferred_backup_window = "00:00-01:00"
  preferred_maintenance_window = "Mon:02:00-Mon:04:00"
  copy_tags_to_snapshot = True
  network_type = "IPV4"
  availability_zones = [
    var.subnet_private1_availability_zone,
    var.subnet_private2_availability_zone
  ]
  serverlessv2_scaling_configuration = {
    MinCapacity = var.aurora_min_capacity
    MaxCapacity = var.aurora_max_capacity
  }
  tags = {
    Name = "${local.stack_name}-RDS-Password"
    EnvironmentTag = var.environment_tag
    CustomerTag = var.customer_tag
    InfrastructureReleaseTag = var.infrastructure_release_tag
    RegionTag = var.region_tag
    ServiceLayerTag = var.service_layer_tag
    StackInteger = var.stack_integer
    StackName = "${local.stack_name}"
  }
}

resource "aws_db_subnet_group" "db_instance_subnet_group" {
  description = "Aurora Subnet Group for platform app server stacks"
  name = "${local.stack_name}-DBSubnetGroup"
  subnet_ids = [
    var.subnet_private1,
    var.subnet_private2
  ]
  tags = {
    Name = "${local.stack_name}-ADO-PAT"
    EnvironmentTag = var.environment_tag
    CustomerTag = var.customer_tag
    InfrastructureReleaseTag = var.infrastructure_release_tag
    RegionTag = var.region_tag
    ServiceLayerTag = var.service_layer_tag
    StackInteger = var.stack_integer
    StackName = "${local.stack_name}"
  }
}

resource "aws_iam_role" "aurora_role" {
  assume_role_policy = {
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = [
            "rds.amazonaws.com"
          ]
        }
        Action = [
          "sts:AssumeRole"
        ]
      }
    ]
  }
  description = "Use for RDS Proxy"
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
  ]
  force_detach_policies = [
    {
      PolicyName = "${local.stack_name}-cluster-db-policy"
      PolicyDocument = {
        Version = "2012-10-17"
        Statement = [
          {
            Effect = "Allow"
            Action = [
              "secretsmanager:GetSecretValue"
            ]
            Resource = var.aurora_sql_secret_arn
          },
          {
            Effect = "Allow"
            Action = [
              "kms:Decrypt"
            ]
            Resource = var.aurora_sql_secret_arn
            Condition = {
              StringEquals = {
                kms:ViaService = "secretsmanager.${data.aws_region.current.name}.amazonaws.com"
              }
            }
          },
          {
            Effect = "Allow"
            Action = [
              "s3:GetBucketLocation"
            ]
            Resource = [
              "arn:aws:s3:::${var.aurora_backups_bucket_name}"
            ]
          },
          {
            Effect = "Allow"
            Action = [
              "s3:ListBucket"
            ]
            Resource = [
              "arn:aws:s3:::${var.aurora_backups_bucket_name}"
            ]
          },
          {
            Effect = "Allow"
            Action = [
              "s3:GetObject"
            ]
            Resource = [
              "arn:aws:s3:::${var.aurora_backups_bucket_name}/*"
            ]
          },
          {
            Effect = "Allow"
            Action = [
              "s3:PutObject"
            ]
            Resource = [
              "arn:aws:s3:::${var.aurora_backups_bucket_name}/*"
            ]
          }
        ]
      }
    }
  ]
  path = "/"
  name = "${local.stack_name}-AuroraRole"
}

output "aurora_role_arn" {
  description = "Returns the ARN of the Aurora Role used for this cluster"
  value = aws_iam_role.aurora_role.arn
}

output "cluster_name" {
  description = "Returns the Cluster name"
  value = aws_rds_cluster.rdsdb_cluster.arn
}

output "cluster_arn" {
  description = "The ARN of the DB ClusterL"
  value = aws_rds_cluster.rdsdb_cluster.arn
}

output "db_endpoint" {
  description = "The RDS DB enpoint from this stack"
  // Unable to resolve Fn::GetAtt with value: [
  //   "RDSDBCluster",
  //   "Endpoint.Address"
  // ]
}

output "db_name" {
  description = "The name of the Database managed by AWS Aurora"
  value = var.db_name
}

output "db_port" {
  description = "The RDS DB port from this stack"
  // Unable to resolve Fn::GetAtt with value: [
  //   "RDSDBCluster",
  //   "Endpoint.Port"
  // ]
}

output "engine_version" {
  description = "The PostgreSQL Engine version we're using"
  value = var.engine_version
}

output "instance_name" {
  description = "The name of the database instance."
  value = aws_rds_cluster.rdsdb_cluster.arn
}

output "postgre_sqlrds_security_group_id" {
  description = "The security group used to manage access to RDS Postgres."
  value = aws_security_group.postgre_sqlrds_security_group.id
}
```

This will likely need lots of manual tweaking, feel free to open up additional issues for mistakes that were made with the conversion.

**Comment by shadycuz** [comment]
I already see one bug, nested attributes in the outputs:
```HCL
output "db_port" {
  description = "The RDS DB port from this stack"
  // Unable to resolve Fn::GetAtt with value: [
  //   "RDSDBCluster",
  //   "Endpoint.Port"
  // ]
}
```

**Comment by j0nathontayl0r** [comment]
Wow, what service. Thanks @shadycuz <3.
