### ISSUE TITLE
InvalidGitRepositoryError

### ISSUE THREAD

**Issue by jannyg** [DontShaveTheYak/cf2tf#29]
Tried the latest release with the fix for #19, but now I get this error message:

````
// Converting cf.cfn to Terraform!
 existing repo found.
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/app.py", line 41, in cli
    search_manger = code.search_manager()
  File "/usr/local/lib/python3.9/site-packages/cf2tf/terraform/code.py", line 53, in search_manager
    repo = get_code()
  File "/usr/local/lib/python3.9/site-packages/cf2tf/terraform/code.py", line 72, in get_code
    repo = Repo(repo_path)
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
````

The cloned repo to ``/tmp/terraform_src`` seems to not have a Git config and running ``git init`` in that folder resulted in the following error:

````
// Converting cf.cfn to Terraform!
 existing repo found.
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(cf_template, search_manger).convert()
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 63, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 115, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 273, in convert_resources
    docs_path = self.search_manager.find(resource_type)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/terraform/code.py", line 39, in find
    resource_name, ranking, doc_path = process.extractOne(
TypeError: cannot unpack non-iterable NoneType object
````

A removal of the ``/tmp/terraform_src`` resulting in a fresh clone fixed the issue. Maybe there could be a check for this folder and clone it again if it fails the checks?

**Comment by shadycuz** [comment]
@jannyg Yeah I think there is a basic check to see if `/tmp/terraform_src` exists, but that's it. It shouldn't be hard to find a way in the `git` package to check if the folder is a valid git repository. Something like `git status` or `git remote -v`. I will look into this. Thanks!

**Comment by robomnis** [comment]
Seeing the same sort of error about InvalidGitRepositoryError (weirdly this was working on my laptop, so maybe the versions changed?)
```
Robs-Mac-Pro:CloudFormation robweaver$ cf2tf vpcpeer.yaml 
// Converting vpcpeer.yaml to Terraform!
 existing repo found.
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cf2tf/app.py", line 41, in cli
    search_manger = code.search_manager()
  File "/usr/local/lib/python3.10/site-packages/cf2tf/terraform/code.py", line 54, in search_manager
    repo = get_code()
  File "/usr/local/lib/python3.10/site-packages/cf2tf/terraform/code.py", line 73, in get_code
    repo = Repo(repo_path)
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
Robs-Mac-Pro:CloudFormation robweaver$ cf2tf glassfish.yaml 
// Converting glassfish.yaml to Terraform!
 existing repo found.
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cf2tf/app.py", line 41, in cli
    search_manger = code.search_manager()
  File "/usr/local/lib/python3.10/site-packages/cf2tf/terraform/code.py", line 54, in search_manager
    repo = get_code()
  File "/usr/local/lib/python3.10/site-packages/cf2tf/terraform/code.py", line 73, in get_code
    repo = Repo(repo_path)
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/usr/local/lib/python3.10/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError
```

**Comment by robomnis** [comment]
I had to do the same with removing the temp folder as mentioned. Took me a bit to figure out how to run tempfile.gettempdir() to figure out where it was, but works after deleting that folder.

`python -c 'import tempfile; print(tempfile.gettempdir())'`
