### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by saxena-anshul** [DontShaveTheYak/cf2tf#38]
Tried the latest release, but I am getting the below error:

```
// Converting Scheduled-Patch-Automation.yaml to Terraform!
Traceback (most recent call last):
  File "/opt/homebrew/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(cf_template, search_manger).convert()
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 71, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 123, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 301, in convert_resources
    resolved_values = self.resolve_values(
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 155, in resolve_values
    data[key] = self.resolve_values(value, allowed_func, prev_func)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in resolve_values
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in <listcomp>
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 155, in resolve_values
    data[key] = self.resolve_values(value, allowed_func, prev_func)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 155, in resolve_values
    data[key] = self.resolve_values(value, allowed_func, prev_func)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in resolve_values
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in <listcomp>
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 155, in resolve_values
    data[key] = self.resolve_values(value, allowed_func, prev_func)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in resolve_values
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 169, in <listcomp>
    return [self.resolve_values(item, allowed_func, prev_func) for item in data]
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/convert.py", line 165, in resolve_values
    return allowed_func[key](self, value)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/conversion/expressions.py", line 652, in sub
    return sub_s(template, values)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/conversion/expressions.py", line 682, in sub_s
    return re.sub(reVar, replace_var, value).replace("${!", "${")
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/conversion/expressions.py", line 676, in replace_var
    result = ref(template, var)
  File "/opt/homebrew/lib/python3.9/site-packages/cf2tf/conversion/expressions.py", line 765, in ref
    if "AWS::" in var_name:
TypeError: argument of type 'NoneType' is not iterable
```

Cloudformation template being used:- [https://github.com/aws-samples/aws-systems-manager-schedule-central-patch-example/blob/main/Templates/Scheduled-Patch-Automation.yaml](url)

**Comment by shadycuz** [comment]
Thanks @saxena-anshul, I will look into this.

**Comment by shadycuz** [comment]
I have found the issue and I will be pushing a fix shortly. In case you don't want to wait, here in the template:

```HCL
data "aws_caller_identity" "current" {
}


data "aws_region" "current" {
}


data "aws_partition" "current" {
}


locals  {
  CreateAutomationAdministrationRoleCondition = var.existing_automation_administration_role == ""
}


variable "event_bridge_rule_schedule" {
  description = "The cron or rate expression to use for the EventBridge rule. For example: cron(0 02 ? * TUE *). Important: The time zone used is UTC. For more information, see https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html."
  type = string
}


variable "execution_role_name" {
  description = "The Automation execution role to be assumed in target accounts during multi-account and multi-Region Automation patching operations."
  type = string
  default = "AWS-SystemsManager-AutomationExecutionRole"
}


variable "existing_automation_administration_role" {
  description = "(Optional) The IAM role ARN of an existing Automation Administration role which has permissions to invoke multi-account and multi-Region Automation workflows."
  type = string
}


variable "maximum_concurrency" {
  description = "Specify the number or percentage of targets on which to execute the task at the same time. You can specify a number, such as 10, or a percentage, such as 10%. The default value is 10%."
  type = string
  default = "10%"
}


variable "maximum_errors" {
  description = "The number of errors that are allowed before the system stops initiating the automation on additional targets. You can specify either an absolute number of errors, for example 10, or a percentage of the target set, for example 10%. The default value is 10%."
  type = string
  default = "10%"
}


variable "run_patch_baseline_operation" {
  description = "(Required) The update or configuration to perform on the instance. The Scan operation checks if patches specified in the patch baseline are installed on the instance. The Install operation installs patches missing from the baseline."
  type = string
  default = "Scan"
}


variable "run_patch_baseline_reboot_option" {
  description = "(Optional) Reboot behavior after a patch Install operation. If you choose NoReboot and patches are installed, the instance is marked as non-compliant until a subsequent reboot and scan."
  type = string
  default = "NoReboot"
}


variable "run_patch_baseline_install_override_list" {
  description = "(Optional) An https URL or an Amazon S3 path-style URL to the list of patches to be installed. This patch installation list overrides the patches specified by the default patch baseline."
  type = string
}


variable "resource_group_name" {
  description = "Enter a resource group that includes the resources you want to target. Important: The Resource Group name is case sensitive."
  type = string
}


variable "target_accounts" {
  description = "Comma separated list of AWS Account Ids for the target account(s)."
  type = string
}


variable "target_location_max_concurrency" {
  description = "Specify the number or percentage of locations (account-Region pairs) on which to execute the task at the same time. You can specify a number, such as 10, or a percentage, such as 10%. The default value is 1."
  type = string
  default = "1"
}


variable "target_location_max_errors" {
  description = "Specify an error threshold which will stop the task after the task fails on a specific number or percentage of locations. You can specify either an absolute number of errors, for example 10, or a percentage of the locations, for example 10%. The default value is 1."
  type = string
  default = "1"
}


variable "target_region_ids" {
  description = "Comma separated list of AWS Regions to target. For example: us-east-1,ap-south-1."
  type = string
}


resource "aws_cloudwatch_event_rule" "event_bridge_rule" {
  description = "EventBridge rule created for scheduled multi-account and multi-Region Automation patching using AWS Lambda and AWS Systems Manager Automation"
  name = "Schedule-Trigger-for-Lambda-MultiAccountPatchingBlog"
  schedule_expression = var.event_bridge_rule_schedule
  // CF Property(State) = "ENABLED"
  // CF Property(Targets) = [{'Arn': 'aws_lambda_function.multi_account_patching_blog_lambda_function.arn', 'Id': '"MultiAccountPatchingBlog"'}]
}


resource "aws_lambda_permission" "permission_for_events_to_invoke_lambda" {
  function_name = aws_lambda_function.multi_account_patching_blog_lambda_function.arn
  action = "lambda:InvokeFunction"
  principal = "events.amazonaws.com"
  source_arn = aws_cloudwatch_event_rule.event_bridge_rule.arn
}


resource "aws_iam_role" "aws_lambda_ssm_multi_account_patching_blog_role" {
  name = "AWS-Lambda-SSM-MultiAccountPatchingBlogRole"
  assume_role_policy = {
    Version = "2012-10-17"
    Statement = [{'Effect': '"Allow"', 'Principal': {'Service': ['"lambda.amazonaws.com"']}, 'Action': '"sts:AssumeRole"'}]
  }
  path = "/"
  force_detach_policies = [{'PolicyName': '"AWSLambdaSSMMultiAccountPatchingBlogPolicy"', 'PolicyDocument': {'Version': '"2012-10-17"', 'Statement': [{'Effect': '"Allow"', 'Action': ['"ssm:StartAutomationExecution"'], 'Resource': ['"arn:${data.aws_partition.current.partition}:ssm:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:automation-definition/${aws_ssm_document.automation_document_mamr_run_patch_baseline.created_date}:$DEFAULT"']}, {'Action': '"iam:PassRole"', 'Resource': '"arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}:role/AWS-SystemsManager-AutomationAdministrationRole"', 'Effect': '"Allow"'}, {'Action': '"logs:CreateLogGroup"', 'Resource': '"arn:${data.aws_partition.current.partition}:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:*"', 'Effect': '"Allow"'}, {'Action': ['"logs:CreateLogStream"', '"logs:PutLogEvents"'], 'Resource': '"arn:${data.aws_partition.current.partition}:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/lambda/MultiAccountPatchingBlog:*"', 'Effect': '"Allow"'}]}}]
}


resource "aws_lambda_function" "multi_account_patching_blog_lambda_function" {
  code_signing_config_arn = {
    ZipFile = "import boto3
import os
import string
import uuid

client = boto3.client('ssm')

def handler(event,context):
    TargetAccounts=os.environ['TargetAccounts']
    b = str(TargetAccounts)
    TargetAccountsArray = b.split(",")
    TargetRegionIds=os.environ['TargetRegionIds']
    b = str(TargetRegionIds)
    TargetRegionIdsArray = b.split(",")
    RunPatchBaselineOperation=os.environ['RunPatchBaselineOperation']
    RunPatchBaselineRebootOption=os.environ['RunPatchBaselineRebootOption']
    RunPatchBaselineInstallOverrideList=os.environ['RunPatchBaselineInstallOverrideList']
    ResourceGroupName=os.environ['ResourceGroupName']
    MaximumConcurrency=os.environ['MaximumConcurrency']
    MaximumErrors=os.environ['MaximumErrors']
    TargetLocationMaxConcurrency=os.environ['TargetLocationMaxConcurrency']
    TargetLocationMaxErrors=os.environ['TargetLocationMaxErrors']
    ExecutionRoleName=os.environ['ExecutionRoleName']
    MasterAccountID=os.environ['MasterAccountID']
    AutomationDocumentMamrRunPatchBaseline=os.environ['AutomationDocumentMamrRunPatchBaseline']
    
    if len(RunPatchBaselineInstallOverrideList) > 0:
        response = client.start_automation_execution(
        DocumentName=f'{AutomationDocumentMamrRunPatchBaseline}',
        
        Parameters={
            'AutomationAssumeRole':[f'arn:aws:iam::{MasterAccountID}:role/AWS-SystemsManager-AutomationAdministrationRole'] ,
            'Operation' : [f'{RunPatchBaselineOperation}'] ,
            'RebootOption' : [f'{RunPatchBaselineRebootOption}'] ,
            'InstallOverrideList' : [f'{RunPatchBaselineInstallOverrideList}'] ,
            'SnapshotId' : [str(uuid.uuid4())]
        },
        TargetLocations=[
            {
                'Accounts': TargetAccountsArray,
                'Regions': TargetRegionIdsArray,
                'TargetLocationMaxConcurrency': f'{TargetLocationMaxConcurrency}',
                'TargetLocationMaxErrors': f'{TargetLocationMaxErrors}',
                'ExecutionRoleName': f'{ExecutionRoleName}'
            }
        ]
    )
    else:
        response = client.start_automation_execution(
        DocumentName=f'{AutomationDocumentMamrRunPatchBaseline}',
        
        Parameters={
            'AutomationAssumeRole':[f'arn:aws:iam::{MasterAccountID}:role/AWS-SystemsManager-AutomationAdministrationRole'] ,
            'Operation' : [f'{RunPatchBaselineOperation}'] ,
            'RebootOption' : [f'{RunPatchBaselineRebootOption}'] ,
            'SnapshotId' : [str(uuid.uuid4())]
        },
        TargetLocations=[
            {
                'Accounts': TargetAccountsArray,
                'Regions': TargetRegionIdsArray,
                'TargetLocationMaxConcurrency': f'{TargetLocationMaxConcurrency}',
                'TargetLocationMaxErrors': f'{TargetLocationMaxErrors}',
                'ExecutionRoleName': f'{ExecutionRoleName}'
            }
        ]
    )
    print(response)
"
  }


  environment {
    variables = {
    TargetAccounts = var.target_accounts
    TargetRegionIds = var.target_region_ids
    RunPatchBaselineOperation = var.run_patch_baseline_operation
    RunPatchBaselineRebootOption = var.run_patch_baseline_reboot_option
    RunPatchBaselineInstallOverrideList = var.run_patch_baseline_install_override_list
    ResourceGroupName = var.resource_group_name
    MaximumConcurrency = var.maximum_concurrency
    MaximumErrors = var.maximum_errors
    TargetLocationMaxConcurrency = var.target_location_max_concurrency
    TargetLocationMaxErrors = var.target_location_max_errors
    ExecutionRoleName = var.execution_role_name
    MasterAccountID = "${data.aws_caller_identity.current.account_id}"
    AutomationDocumentMamrRunPatchBaseline = aws_ssm_document.automation_document_mamr_run_patch_baseline.created_date
  }
  }
  function_name = "MultiAccountPatchingBlog"
  handler = "index.handler"
  role = aws_iam_role.aws_lambda_ssm_multi_account_patching_blog_role.arn
  runtime = "python3.7"
}


resource "aws_iam_role" "automation_administration_service_role" {
  name = "AWS-SystemsManager-AutomationAdministrationRole"
  assume_role_policy = {
    Version = "2012-10-17"
    Statement = [{'Effect': '"Allow"', 'Principal': {'Service': '"ssm.amazonaws.com"'}, 'Action': ['"sts:AssumeRole"']}]
  }
  path = "/"
  force_detach_policies = [{'PolicyName': '"AssumeRole-AWSSystemsManagerAutomationExecutionRole"', 'PolicyDocument': {'Version': '"2012-10-17"', 'Statement': [{'Effect': '"Allow"', 'Action': ['"sts:AssumeRole"'], 'Resource': '"arn:${data.aws_partition.current.partition}:iam::*:role/AWS-SystemsManager-AutomationExecutionRole"'}, {'Effect': '"Allow"', 'Action': ['"organizations:ListAccountsForParent"'], 'Resource': ['"*"']}]}}]
}


resource "aws_ssm_document" "automation_document_mamr_run_patch_baseline" {
  name = "Automation-RunPatchBaseline"
  document_type = "Automation"
  content = {
    description = "**Description**
This document runs the Command document ```AWS-RunPatchBaseline``` on the specified instances."
    schemaVersion = "0.3"
    assumeRole = "{{ AutomationAssumeRole }}"
    parameters = {
      AutomationAssumeRole = {
        type = "String"
        description = "The ARN of the Automation service role to assume."
      }
      Operation = {
        type = "String"
        default = "Scan"
        description = "(Required) The update or configuration to perform on the instance. The system checks if patches specified in the patch baseline are installed on the instance. The install operation installs patches missing from the baseline."
      }
      RebootOption = {
        type = "String"
        default = "RebootIfNeeded"
        description = "(Optional) Reboot behavior after a patch Install operation. If you choose NoReboot and patches are installed, the instance is marked as non-compliant  until a subsequent reboot and scan."
      }
      InstallOverrideList = {
        type = "String"
        default = ""
        description = "(Optional) An https URL or an Amazon S3 path-style URL to the list of patches to be installed. This patch installation list overrides the patches specified by the default patch baseline."
      }
      SnapshotId = {
        type = "String"
        default = ""
        description = "(Optional) The snapshot ID to use to retrieve a patch baseline snapshot."
      }
    }
    mainSteps = [{'name': '"runPatchBaseline"', 'action': '"aws:runCommand"', 'timeoutSeconds': '"7200"', 'onFailure': '"Abort"', 'inputs': {'DocumentName': '"AWS-RunPatchBaseline"', 'Targets': [{'Key': '"resource-groups:Name"', 'Values': ['var.resource_group_name']}], 'Parameters': {'Operation': '"{{ Operation }}"', 'RebootOption': '"{{ RebootOption }}"', 'SnapshotId': '"{{ SnapshotId }}"', 'InstallOverrideList': '"{{ InstallOverrideList }}"'}, 'MaxConcurrency': 'var.maximum_concurrency', 'MaxErrors': 'var.maximum_errors'}, 'description': '"This command runs the Command document ```AWS-RunPatchBaseline``` on the specified instances."'}]
  }
}
```

Just note that their will be lots of manual work to make this work 100% in Terraform. But we are hoping to reduce the manual work in future versions.

**Comment by shadycuz** [comment]
The new version has been released =)

**Comment by saxena-anshul** [comment]
Thanks @shadycuz
